### ISSUE TITLE
do you know python packages to simulate implicit  data for recommender systems pls 

### ISSUE THREAD

**Issue by Sandy4321** [KID-22/CTAR#2]
do you know python packages to simulate implicit  data for recommender systems pls

**Comment by KID-22** [comment]
Sorry, I have no idea. But maybe you can refer to Report on the 1st simulation for information retrieval workshop (Sim4IR 2021) at SIGIR 2021.

**Comment by Sandy4321** [comment]
thanks for idea, but nothing is there
